version: '3.8'

services:
  # NestJS 后端服务
  core:
    build:
      context: .
      dockerfile: Dockerfile
      target: core
    container_name: redgent-core
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_SECRET: ${REDDIT_SECRET}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      PROXY_URL: ${PROXY_URL:-}
    networks:
      - redgent-network
    restart: unless-stopped

  # React 前端服务
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: redgent-web
    ports:
      - '3000:3000'
    depends_on:
      - core
    networks:
      - redgent-network
    restart: unless-stopped

networks:
  redgent-network:
    driver: bridge
