#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running lint-staged..."
npx lint-staged

echo "📝 Type checking..."
pnpm typecheck

echo "🧪 Running unit tests..."
pnpm test

echo "✅ All pre-commit checks passed!"
